version: "3.3"
   
services:
        app:
                image: hw
                build: .
                ports:
                        - "8080:8080"
        
        redis:
                image: redis 
